osx_image: xcode8.3
sudo: required
dist: trusty
language: c

#env:
#  global:
#    - GH_TOKEN: RWrGDiC1fhng5j1yighCYP7UUjcR4L+PiSG1gj7vNfeqwFLijBThRlg5R5UzE+QVzRRS1jn0AURoCCKbElMFzTGMgwuzAsJn+wO2la35KQ6aExXv4O/63sQ+6zopwRV+on5nXi01vuC1qg1XbLuk+uudqdPQYE/lGuz9faqUYTgJarlT/pw/FCYycawMr4miSGKz0B49RGEiHiDf20QRQUp6Mn1IAmKMvxUyl9bcfv2Ema5WxVIB4WGSZTTaNdSfDUYSI93UvNu8NO2mJbWB14Wl9TYpDZ0dst0krrv69AR2n1izNZ0Na9nSytF3Lq/x28IW8vetobakD05fuROfkjIKURxNYPb6UMpT9iCN4/bjR5QZ/tW3jVLgMWPmVJwPnudwKZmmhl2e7qq0V+jUfLzW/iKvf2ijnStJtJ+plpW7ZGt74F/RGVzQ5LovTHmgOPeNX5U7eAAprmFM5OHTsqJAOYuCxbL7no6u0Okocg7d1e5A2UNXZVB+NfUCN5GzDNqR+bs+4/S0DVkeJBkoxKj6UUBWL9yrrHOW3GBUOI0x4/96UbURF5U7IXN6E244MRTBJs33rqQ58jZk5llVDiQoc6S5ZkzIcc89V61Fv37C/jKA+e+Dk+lDTz2FWwsrIDC7XzWLGIAOUAL6CfIgCJszJviyh01PZFRm7CRGf6k=
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
    "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
    | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
- npm run publish
branches:
  only:
  - master
