osx_image: xcode8.3
sudo: required
dist: trusty
language: c
env:
  global:
    - GH_TOKEN: "p9YpAz0DwEHACNOMy1SsFEvzM7oZ9655ZeCRmbplggZRN105kXM4nQF8eSrTQIf1CnDMUno4qSeZVy8X6E4febYar1+glIkb7cOAAqyE0IgPRqS0pgf8zwsBVgueQ7nw1NItizMcXJPdQGHHpkspAP+w9x2TrF0p+SmGFole9Y5fPsHi+KBNX98/JqQ+S/1oq01rgHEef+CehXRMqyqWWWVu/Cr3zs3tjEn0kP7IKvk/nwBIc9sZOJ+o4kJh/UVo/RJ/EpDWHkCucwC0LMdNaNhGRqHx32QKQOQ9nYzKYOv4oJtAVhImq7R+hwKE+fRnjcNdE4yQLuX7DgN6KtRdeGKymBNmnj9LzXbkOt74AmRQocPGToRlLxPHgNCpkKpxocM+uorXhXtQ/IDVWSeTOzrvcHEClo+OOBixofvZ6vt3S6biboLhW01TV0PuuviqvjG7SvhuLJZMcAl12Jy+bK5JVBZnhYqZn7a8FX3J4oPbm4QpiLrTGHkGpWKvFP25z8pk7Kq0jRlX0cjMBXoBByd/e/lGIaFXl2c35ZswBmtxqOUckV8g9D+xpR8RrLgbO/Temcm+kxlSxx/esHTKrEIH8Ccn59mmxTq6eQly6XDsgz7D5aro0uenrALHQBxsMf8s2Y2+lJg5g9z9B+h6xtg/JqhToO3UQQLIXFPO6u4="
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
    "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
    | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
- npm run publish
branches:
  only:
  - master
